### ISSUE TITLE
how to display css helpers (red arrow and borders) while dragging element

### ISSUE THREAD

**Issue by masterdany88** [johnny/jquery-sortable#155]
Hey. On Your demos while dragging elements I can see a lot of many usefull helpers. But When I am trying to run on my server I dont any of them. Also in Your documentation there is no word mentioned about it. Can You give me some help with it?

Here is an print screen of helpers I ask:
![image](https://cloud.githubusercontent.com/assets/1161910/5419884/e8426daa-824f-11e4-92ed-3bd505a42a5f.png)

**Comment by roartex** [comment]
You can change how the placeholder displays to however you like. I have amended the CSS to show a big fat bar instead of the default.

CSS: 
.placeholder {
position: relative;
padding:0; height:0; 
width: 100%; height:0;
}
.placeholder:before { 
z-index: 1000; width:100%; height:12px; background: #d9d9d9; top:-8px; left:0; padding-top:4px; box-shadow:0 1px 2px rgba(0,0,0,0.2); opacity: 0.8; filter:alpha(opacity=80);
}

**Comment by johnny** [comment]
@roartex correct. Thanks

**Comment by mirko77** [comment]
@johnny  what about this statement: `Moreover this plugin assumes that the placeholder has zero height/width.`

What happens if I have a `height:20px;` for example?
