### ISSUE TITLE
How to display red caret for position

### ISSUE THREAD

**Issue by jlombardo** [johnny/jquery-sortable#157]
Nice plugin. Thanks for a great tool!. I'm having trouble getting the red caret to display, however. Everything else works fine. I'm using Bootstrap 3.3.1. Could that be the problem?

**Comment by roartex** [comment]
You can change how the placeholder displays to however you like. I have amended the CSS to show a big fat bar instead of the default. 

CSS: 
.placeholder {
  position: relative;
  padding:0; height:0; 
  width: 100%; height:0;
}
.placeholder:before { 
z-index: 1000; width:100%; height:12px; background: #d9d9d9; top:-8px; left:0;  padding-top:4px;  box-shadow:0 1px 2px rgba(0,0,0,0.2); opacity: 0.8; filter:alpha(opacity=80);
}

**Comment by johnny** [comment]
Bootstrap should not be a problem. You will need to define a pseudo element as @roartex demonstrated.
